# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest]
        node-version: [14, 16, 18, 20]
    name: Node.js ${{ matrix.node-version }} Test on ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test-cov
      # - uses: codecov/codecov-action@v3
      #   with:
      #     name: codecov-node-cli # optional
      #     fail_ci_if_error: true # optional (default = false)
      #     verbose: true # optional (default = false)
